import { readFileSync } from 'node:fs'
import { join } from 'node:path'

/**
 * Bundled Stedi payer directory (generated by scripts/build-payer-directory.ts).
 * Server-only: loaded from disk once per process. ~3,600 payers with their
 * Stedi payer id, supported transactions, and which ones require enrollment.
 */

export interface StediPayer {
  stediId: string
  payerId: string
  name: string
  states: string[]
  professionalClaim: boolean
  professionalClaimEnrollmentRequired: boolean
  era: boolean
  eraEnrollmentRequired: boolean
  eligibility: boolean
  eligibilityEnrollmentRequired: boolean
  claimStatus: boolean
}

let cache: StediPayer[] | null = null

export function allPayers(): StediPayer[] {
  if (!cache) {
    const path = join(process.cwd(), 'lib/rcm/payers/stedi-payers.json')
    cache = JSON.parse(readFileSync(path, 'utf8')) as StediPayer[]
  }
  return cache
}

export function payerById(payerId: string): StediPayer | undefined {
  return allPayers().find((p) => p.payerId === payerId)
}

export interface PayerQuery {
  q?: string
  state?: string
  limit?: number
  offset?: number
}

/** Search by name or payer id, optionally filtered to a state. Returns a capped page + total. */
export function searchPayers({ q, state, limit = 50, offset = 0 }: PayerQuery): { total: number; results: StediPayer[] } {
  const needle = (q ?? '').trim().toLowerCase()
  let list = allPayers()
  if (state) list = list.filter((p) => p.states.includes(state))
  if (needle) {
    list = list.filter((p) => p.name.toLowerCase().includes(needle) || p.payerId.toLowerCase().includes(needle))
  }
  return { total: list.length, results: list.slice(offset, offset + limit) }
}
